version: "3"

services:
  icbig-01-01:
    image: viprore/cluster-control:HEAD
    hostname: icbig-01-01
    tty: true
    privileged: true
    ports:
      - 5432:5432
      - 9999:9999
    volumes:
      - ./shared:/srv
    networks:
      mhadoop-network:
        ipv4_address: 172.18.0.101

  icbig-01-02:
    image: viprore/cluster-base:HEAD
    hostname: icbig-01-02
    tty: true
    privileged: true
    networks:
      mhadoop-network:
        ipv4_address: 172.18.0.102

  icbig-01-03:
    image: viprore/cluster-base:HEAD
    hostname: icbig-01-03
    tty: true
    privileged: true
    networks:
      mhadoop-network:
        ipv4_address: 172.18.0.103

networks:
  mhadoop-network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16