version: "3"

services:
  icbig-01-01:
    image: viprore/cluster-control:HEAD
    hostname: icbig-01-01
    tty: true
    privileged: true
    ports:
      - 5432:5432
      - 9999:9999
    volumes:
      - ./shared:/srv

  icbig-01-02:
    image: viprore/cluster-base:HEAD
    hostname: icbig-01-02
    tty: true
    privileged: true

  icbig-01-03:
    image: viprore/cluster-base:HEAD
    hostname: icbig-01-03
    tty: true
    privileged: true

networks:
  default:
    name: mhadoop-network