---


- name: check data dir and initdb
  tags: [ install ]
  block:
    - name: data dir check
      find:
        paths: "{{ postgresql.dir.data }}"
      register: filesFound
    - name: master init
      when: filesFound.matched == 0
      shell:
        cmd: /usr/bin/postgresql-13-setup initdb

- name: 5. replication/pgpool 유저 생성
  block:
    - name: 5-1. service on
      systemd:
        name: postgresql-13
        state: started
    - name: 5-3. postgres user change password
      become_user: postgres
      become: true
      postgresql_user:
        name: "{{ pgpool.users.recovery.name }}"
        password: "{{ pgpool.users.recovery.password }}"
    - name: 5-2. replication user account
      become_user: postgres
      become: true
      postgresql_user:
        name: "{{ postgresql.replication.user.name }}"
        password: "{{ postgresql.replication.user.password }}"
        role_attr_flags: REPLICATION
        state: present
      environment:
        PGOPTIONS: "-c password_encryption=scram-sha-256"
    - name: 5-3. pgpool user account
      become_user: postgres
      become: true
      postgresql_user:
        name: "{{ pgpool.users.pgpool.name }}"
        password: "{{ pgpool.users.pgpool.password }}"
        role_attr_flags: LOGIN
        state: present
      environment:
        PGOPTIONS: "-c password_encryption=scram-sha-256"
    - name: grant pg_monitor
      become: true
      become_user: postgres
      postgresql_membership:
        groups: pg_monitor
        target_roles: pgpool
        state: present
    - name: 5-4. service stop
      systemd:
        name: postgresql-13
        state: stopped

# replica 설정이 들어가버리면 5. 태스크 수행이 불가. 부득이하게 순서 변경
- name: 6. postgresql config 수정
  template:
    src: templates/pgsql/{{ item }}.j2
    dest: "{{ postgresql.dir.data }}/{{ item }}"
    owner: postgres
    group: postgres
  loop:
    - postgresql.conf
    - pg_hba.conf

- name: 7. slave에서 백업 받도록 service on
  systemd:
    name: postgresql-13
    state: started

...
