---
- name: postgresql13-server 설치
  yum:
    state: present
    name:
      - postgresql13-server-13.4-1PGDG.rhel7.x86_64
      - python-psycopg2
  tags: [ install ]

- name: postgresql data dir 생성
  tags: [ install ]
  file:
    path: "{{ postgresql.dir.data }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: postgresql log dir 생성
  tags: [ install ]
  file:
    path: "{{ postgresql.dir.log }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'

- name: disabled postgresql-13 service
  systemd:
    name: postgresql-13
    enabled: no
...
