---
- name: postgres backup start
  debug:
    msg:
      - "component_name : {{ component_name }}"
      - "target_hosts : {{ target_group|default(component_name|default('none')) }}"
      - "collect_location : {{ config.collect_dir }}"
      - "config_location : {{ config.postgres.dir }}"
      - "collect_unit : {{ '폴더' if not config.postgres.files else '파일[' + ','.join(config.postgres.files) +']' }}"

- name: copy config
  block:
    - name: create before/after directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ config.collect_dir }}/postgres/before"
        - "{{ config.collect_dir }}/postgres/after"

    - name: copy directory
      when: not config.postgres.files
      shell: |
        cp -r {{ config.postgres.dir }} {{ config.collect_dir }}/postgres/before
        cp -r {{ config.postgres.dir }} {{ config.collect_dir }}/postgres/after

    - name: copy files
      when: config.postgres.files
      shell: |
        cp -r {{ config.postgres.dir }}/{{ item }} {{ config.collect_dir }}/postgres/before
        cp -r {{ config.postgres.dir }}/{{ item }} {{ config.collect_dir }}/postgres/after
      with_items: "{{ config.postgres.files }}"

- name: postgres configuration template
  template:
    src: postgres/{{ item }}.j2
    dest: "{{ config.collect_dir }}/postgres/after/{{ item }}"
  with_items: "{{ config.postgres.files }}"

...